name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      suite:
        description: "Test suite to run"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - ui
          - api
          - security
          - smoke
          - auth
          - search
          - basket
      project:
        description: "Browser"
        required: true
        default: "chromium"
        type: choice
        options:
          - chromium
          - firefox
          - webkit
          - all
      grep:
        description: "Optional grep"
        required: false
        default: ""
        type: string

jobs:
  test:
    uses: ./.github/workflows/_run-tests.yml
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      suite: ${{ github.event.inputs.suite || 'all' }}
      project: ${{ github.event.inputs.project || 'chromium' }}
      grep: ${{ github.event.inputs.grep || '' }}
      workflow-name: CI Tests
      node-version: "24"
      timeout-minutes: 60
      upload-allure: true
      upload-console-results: false
      publish-pages-report: true
      pages-report-path: allure-report
      pages-report-name: Allure report
      notify-slack: true
      stop-containers: true
    secrets: inherit
